# Elliptical Fourier Analysis

## Load packages + data

```{r load.packages.efa, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# load packages
library(here)
library(Momocs)

# read images
jpg.list <- list.files(here("supp/jpegs"), full.names = TRUE)

# read attribute data
att.data <- read.csv("qdata.csv", header = TRUE, as.is = TRUE)

# attributes to factors
att.data$context <- as.factor(att.data$context)
```

## Generate outlines

```{r outlines + attributes, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# generate outlines
outlines <- jpg.list %>%
  import_jpg()

# add attributes
data.out <- Out(outlines, 
         fac = att.data)

# scale, align, rotate, and center specimens
norm.outlines <- data.out %>% 
  coo_scale() %>%
  coo_align() %>% 
  coo_rotate() %>% 
  coo_center()

# outlines by context

## mounds plantation burial pit 2
mpbp2 <- filter(norm.outlines, 
                context %in% c("16cd12-bp2"))

mpbp2 <- mpbp2 %>% 
  coo_scale() %>%
  coo_align() %>%
  coo_rotate() %>% 
  coo_center()

## mounds plantation burial pit 5
mpbp5 <- filter(norm.outlines, 
                context %in% c("16cd12-bp5"))

mpbp5 <- mpbp5 %>% 
  coo_scale() %>%
  coo_align() %>%
  coo_rotate() %>% 
  coo_center()

## gahagan mound burial pit 2
gmbp2 <- filter(norm.outlines, 
                context %in% c("16rr1-bp2"))

gmbp2 <- gmbp2 %>% 
  coo_scale() %>%
  coo_align() %>%
  coo_rotate() %>% 
  coo_center()

## gahagan mound burial pit 3
gmbp3 <- filter(norm.outlines, 
                context %in% c("16rr1-bp3"))

gmbp3 <- gmbp3 %>% 
  coo_scale() %>%
  coo_align() %>%
  coo_rotate() %>% 
  coo_center()

## george c davis feature 119
gcd119 <- filter(norm.outlines, 
                 context %in% c("41ce19-f119"))

gcd119 <- gcd119 %>% 
  coo_scale() %>%
  coo_align() %>%
  coo_rotate() %>% 
  coo_center()

## george c davis feature 134
gcd134 <- filter(norm.outlines, 
                 context %in% c("41ce19-f134"))

gcd134 <- gcd134 %>% 
  coo_scale() %>%
  coo_align() %>%
  coo_rotate() %>% 
  coo_center()

# render figure
par(mfrow=c(2, 3))
stack(mpbp2, title = "Mounds Plantation, Burial Pit 2", xy.axis = TRUE, centroid = FALSE)
stack(mpbp5, title = "Mounds Plantation, Burial Pit 5", xy.axis = TRUE, centroid = FALSE)
stack(gmbp2, title = "Gahagan Mound, Burial Pit 2", xy.axis = TRUE, centroid = FALSE)
stack(gmbp3, title = "Gahagan Mound, Burial Pit 3", xy.axis = TRUE, centroid = FALSE)
stack(gcd119, title = "George C. Davis, Feature 119", xy.axis = TRUE, centroid = FALSE)
stack(gcd134, title = "George C. Davis, Feature 134", xy.axis = TRUE, centroid = FALSE)
```

## Pile and mosaics

```{r stack.panel, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# outline pile
pile(norm.outlines)
```

## Calibrate harmonic + EFA

```{r cal.harm, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# calibrate how many harmonics needed
calibrate_harmonicpower_efourier(norm.outlines, 
                                 nb.h = 30)

# 10 harmonics needed to capture 99 percent of variation
calibrate_reconstructions_efourier(norm.outlines, 
                                   range = 1:10)

# generate efa outlines with 10 harmonics
efa.outlines <- efourier(norm.outlines, 
                         nb.h = 10, 
                         norm = TRUE)

# use efa.outlines for pca
pca.outlines <- PCA(efa.outlines)
```

## PCA

```{r pca.plot, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# pca 
scree_plot(pca.outlines)

# plot pca by region
plot_PCA(pca.outlines, 
         morphospace_position = "range",
         ~context, zoom = 1.25)

# contribution of each pc by region2
boxplot(pca.outlines, ~context, nax = 1:5)

# mean shape + 2sd for the first 10 pcs
PCcontrib(pca.outlines, nax = 1:5)
```

## MANOVA + MANOVA_PW

```{r manova, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# manova + manova_pw
# are there shape differences between regions?
MANOVA(pca.outlines, 'context')

# which differ?
MANOVA_PW(pca.outlines, 'context')
```

## Mean shapes

```{r ms1, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE, fig.cap="Mean shapes for Gahagan bifaces by burial context."}
# mean shapes for regions
ms.1 <- MSHAPES(efa.outlines, ~context)
plot_MSHAPES(ms.1, size = 0.75)
```
