# Elliptical Fourier Analysis

## Load packages + data

```{r load.packages, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# load packages
library(here)
library(Momocs)

# read images
jpg.list <- list.files(here("/jpegs"), full.names = TRUE)

# read attribute data
att.data <- read.csv("qdata.csv", header = TRUE, as.is = TRUE)

# attributes to factors
att.data$sitename <- as.factor(att.data$sitename)
att.data$region2 <- as.factor(att.data$region2)
```

## Generate outlines

```{r outlines + attributes, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# generate outlines
outlines <- jpg.list %>%
  import_jpg()

# add attributes
data.out <- Out(outlines, 
         fac = att.data)

# scale, align, rotate, and center specimens
norm.outlines <- data.out %>% 
  coo_scale() %>%
  coo_align() %>% 
  coo_rotate() %>% 
  coo_center()
```

## Pile and mosaics

```{r stack.panel, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# outline pile
pile(norm.outlines)

# mosaic of individual specimens from the different sites
mosaic(norm.outlines, ~region2)
```

## Calibrate harmonic + EFA

```{r cal.harm, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# calibrate how many harmonics needed
calibrate_harmonicpower_efourier(norm.outlines, 
                                 nb.h = 30)

# 11 harmonics needed to capture 99 percent of variation
calibrate_reconstructions_efourier(norm.outlines, 
                                   range = 1:11)

# generate efa outlines with 11 harmonics
efa.outlines <- efourier(norm.outlines, 
                         nb.h = 11, 
                         norm = TRUE)

# use efa.outlines for pca
pca.outlines <- PCA(efa.outlines)
```

## PCA

```{r pca.plot, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# pca 
scree_plot(pca.outlines)

# plot pca by site
plot_PCA(pca.outlines, 
         morphospace_position = "range",
         ~site, zoom = 1.25)

# contribution of each pc
boxplot(pca.outlines, ~site, nax = 1:5)

# mean shape + 2sd for the first 10 pcs
PCcontrib(pca.outlines, nax = 1:10)
```

## MANOVA + MANOVA_PW

```{r manova, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
# manova + manova_pw
# is there shape differences between sites?
MANOVA(pca.outlines, 'site')

# which differ?
MANOVA_PW(pca.outlines, 'site')
```

## Mean shapes

```{r ms1, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE, fig.cap="Mean shapes for Gahagan bifaces by site."}
# mean shapes
ms.1 <- MSHAPES(efa.outlines, ~site)
plot_MSHAPES(ms.1, size = 0.75)
```
